# Generated by Django 4.2.11 on 2026-03-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('EXECUTIVE', 'Executive'), ('HR', 'HR'), ('CHR', 'CHR')], default='HR', max_length=20),
        ),
    ]
