# Generated by Django 4.2.11 on 2026-03-14 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0002_employee_org_and_owner_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_meetingparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_file',
            field=models.FileField(blank=True, null=True, upload_to='meetings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MeetingTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='meetings.meeting')),
            ],
            options={
                'ordering': ['meeting_id', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSpeakerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_mappings', to='employees.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_mappings', to='meetings.meeting')),
            ],
            options={
                'ordering': ['meeting_id', 'speaker_label'],
                'unique_together': {('meeting', 'speaker_label')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeMeetingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_duration', models.FloatField(default=0.0)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('speaking_turns', models.PositiveIntegerField(default=0)),
                ('interruption_signals', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_insights', to='employees.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_insights', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-meeting__date', '-id'],
                'unique_together': {('employee', 'meeting')},
            },
        ),
    ]
