# Generated by Django 4.2.11 on 2026-03-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_org_and_owner_fields'),
        ('meetings', '0003_meeting_department_meeting_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranscript',
            name='speaker_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoken_transcript_segments', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='MeetingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('SUMMARY', 'Summary'), ('ACTION_ITEM', 'Action Item'), ('TOPIC', 'Topic'), ('RISK', 'Risk')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
