# Generated by Django 4.2.11 on 2026-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingtranscript_speaker_employee_meetinginsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='speaking_turns',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
