# Generated by Django 4.2.11 on 2026-03-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('career_goals', models.TextField(blank=True, default='')),
                ('concerns', models.TextField(blank=True, default='')),
                ('burnout_risk', models.FloatField(default=0.0)),
                ('strengths', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='employees.employee')),
            ],
        ),
    ]
